from mtglabels.config import defaults

icon_margin_x = 2
icon_margin_y = 2
icon_size = 7

text_line_margin_x = 1
text_line_1_margin_y = 7
text_line_2_margin_y = 15
cut_line_length = 2

label_elements = [
    {
        "name": "top-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": 0,
        "y2": cut_line_length,
    },
    {
        "name": "top-right-horizontal",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": 0,
        "x2": defaults.DIVIDER_WIDTH - cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-right-vertical",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": 0,
        "x2": defaults.DIVIDER_WIDTH,
        "y2": cut_line_length,
    },
    {
        "name": "bottom-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": 0,
        "y2": defaults.DIVIDER_HEIGHT - cut_line_length,
    },
    {
        "name": "bottom-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": cut_line_length,
        "y2": defaults.DIVIDER_HEIGHT,
    },
    {
        "name": "bottom-right-vertical",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": defaults.DIVIDER_WIDTH,
        "y2": defaults.DIVIDER_HEIGHT - cut_line_length,
    },
    {
        "name": "bottom-right-horizontal",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": defaults.DIVIDER_WIDTH - cut_line_length,
        "y2": defaults.DIVIDER_HEIGHT,
    },
    {
        "name": "text_line_1",
        "type": "T",
        "x1": text_line_margin_x,
        "y1": text_line_1_margin_y,
        "x2": 0,
        "y2": 0,
        "size": 10,
        "text": "Label",
    },
    {
        "name": "text_line_2",
        "type": "T",
        "x1": text_line_margin_x,
        "y1": text_line_2_margin_y,
        "x2": 0,
        "y2": 0,
        "size": 8,
        "text": "Label",
    },
    {
        "name": "set_icon",
        "type": "I",
        "x1": defaults.DIVIDER_WIDTH - icon_size - icon_margin_x - 8,
        "y1": icon_margin_y,
        "x2": defaults.DIVIDER_WIDTH - icon_margin_x - 8,
        "y2": icon_size + icon_margin_y,
        "keep_aspect_ratio": True,
    },
    {
        "name": "pip_icon",
        "type": "I",
        "x1": defaults.DIVIDER_WIDTH - icon_size - icon_margin_x,
        "y1": icon_margin_y,
        "x2": defaults.DIVIDER_WIDTH - icon_margin_x,
        "y2": icon_size + icon_margin_y,
        "keep_aspect_ratio": True,
    },
]

label_elements_no_pips = [
    {
        "name": "top-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": 0,
        "y2": cut_line_length,
    },
    {
        "name": "top-right-horizontal",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": 0,
        "x2": defaults.DIVIDER_WIDTH - cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-right-vertical",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": 0,
        "x2": defaults.DIVIDER_WIDTH,
        "y2": cut_line_length,
    },
    {
        "name": "bottom-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": 0,
        "y2": defaults.DIVIDER_HEIGHT - cut_line_length,
    },
    {
        "name": "bottom-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": cut_line_length,
        "y2": defaults.DIVIDER_HEIGHT,
    },
    {
        "name": "bottom-right-vertical",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": defaults.DIVIDER_WIDTH,
        "y2": defaults.DIVIDER_HEIGHT - cut_line_length,
    },
    {
        "name": "bottom-right-horizontal",
        "type": "L",
        "x1": defaults.DIVIDER_WIDTH,
        "y1": defaults.DIVIDER_HEIGHT,
        "x2": defaults.DIVIDER_WIDTH - cut_line_length,
        "y2": defaults.DIVIDER_HEIGHT,
    },
    {
        "name": "text_line_1",
        "type": "T",
        "x1": text_line_margin_x,
        "y1": text_line_1_margin_y,
        "x2": 0,
        "y2": 0,
        "size": 10,
        "text": "Label",
    },
    {
        "name": "text_line_2",
        "type": "T",
        "x1": text_line_margin_x,
        "y1": text_line_2_margin_y,
        "x2": 0,
        "y2": 0,
        "size": 8,
        "text": "Label",
    },
    {
        "name": "set_icon",
        "type": "I",
        "x1": defaults.DIVIDER_WIDTH - icon_size - icon_margin_x,
        "y1": icon_margin_y,
        "x2": defaults.DIVIDER_WIDTH - icon_margin_x,
        "y2": icon_size + icon_margin_y,
        "keep_aspect_ratio": True,
    },
]
