# MTG Card Size: 63mm x 88mm
# Label Size: 65mm x 95mm
divider_width = 65
divider_height = 95

icon_label_margin = 2
text_label_margin = 1
cut_line_length = 2

label_elements = [
    {
        "name": "top-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": 0,
        "y2": cut_line_length,
    },
    {
        "name": "top-right-horizontal",
        "type": "L",
        "x1": divider_width,
        "y1": 0,
        "x2": divider_width - cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-right-vertical",
        "type": "L",
        "x1": divider_width,
        "y1": 0,
        "x2": divider_width,
        "y2": cut_line_length,
    },
    {
        "name": "bottom-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": divider_height,
        "x2": 0,
        "y2": divider_height - cut_line_length,
    },
    {
        "name": "bottom-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": divider_height,
        "x2": cut_line_length,
        "y2": divider_height,
    },
    {
        "name": "bottom-right-vertical",
        "type": "L",
        "x1": divider_width,
        "y1": divider_height,
        "x2": divider_width,
        "y2": divider_height - cut_line_length,
    },
    {
        "name": "bottom-right-horizontal",
        "type": "L",
        "x1": divider_width,
        "y1": divider_height,
        "x2": divider_width - cut_line_length,
        "y2": divider_height,
    },
    {
        "name": "text_line_1",
        "type": "T",
        "x1": text_label_margin,
        "y1": 10,
        "x2": 0,
        "y2": 0,
        "size": 10,
        "text": "Label",
    },
    {
        "name": "text_line_2",
        "type": "T",
        "x1": text_label_margin,
        "y1": 20,
        "x2": 0,
        "y2": 0,
        "size": 8,
        "text": "Label",
    },
    {
        "name": "set_icon",
        "type": "I",
        "x1": divider_width - icon_label_margin - 8,
        "y1": 4,
        "x2": divider_width - 7 - icon_label_margin - 8,
        "y2": 7 + 4,
    },
    {
        "name": "colour_icon",
        "type": "I",
        "x1": divider_width - icon_label_margin,
        "y1": 4,
        "x2": divider_width - 7 - icon_label_margin,
        "y2": 7 + 4,
    },
]

label_elements_no_pips = [
    {
        "name": "top-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": 0,
        "x2": 0,
        "y2": cut_line_length,
    },
    {
        "name": "top-right-horizontal",
        "type": "L",
        "x1": divider_width,
        "y1": 0,
        "x2": divider_width - cut_line_length,
        "y2": 0,
    },
    {
        "name": "top-right-vertical",
        "type": "L",
        "x1": divider_width,
        "y1": 0,
        "x2": divider_width,
        "y2": cut_line_length,
    },
    {
        "name": "bottom-left-vertical",
        "type": "L",
        "x1": 0,
        "y1": divider_height,
        "x2": 0,
        "y2": divider_height - cut_line_length,
    },
    {
        "name": "bottom-left-horizontal",
        "type": "L",
        "x1": 0,
        "y1": divider_height,
        "x2": cut_line_length,
        "y2": divider_height,
    },
    {
        "name": "bottom-right-vertical",
        "type": "L",
        "x1": divider_width,
        "y1": divider_height,
        "x2": divider_width,
        "y2": divider_height - cut_line_length,
    },
    {
        "name": "bottom-right-horizontal",
        "type": "L",
        "x1": divider_width,
        "y1": divider_height,
        "x2": divider_width - cut_line_length,
        "y2": divider_height,
    },
    {
        "name": "text_line_1",
        "type": "T",
        "x1": text_label_margin,
        "y1": 10,
        "x2": 0,
        "y2": 0,
        "size": 10,
        "text": "Label",
    },
    {
        "name": "text_line_2",
        "type": "T",
        "x1": text_label_margin,
        "y1": 20,
        "x2": 0,
        "y2": 0,
        "size": 8,
        "text": "Label",
    },
    {
        "name": "set_icon",
        "type": "I",
        "x1": divider_width - icon_label_margin,
        "y1": 4,
        "x2": divider_width - 7 - icon_label_margin,
        "y2": 7 + 4,
    },
]
